### ISSUE TITLE
ProductProductOdooModel not recognised

### ISSUE THREAD

**Issue by JRB202** [Intechnity-com/OdooJsonRpcClient#71]
This C# line of your OdooJsonRpcClient example :

var repository = new OdooRepository<ProductProductOdooModel>(config);

is transformed into this one in VB
Dim repository = New OdooRepository(Of ProductProductOdooModel)(config)

But ProductProductOdooModel is not recognized by compiler

and in your examples ProductProductOdooModel is never declared 

How can I make ProductProductOdooModel reference recognised ?

**Comment by patricoos** [comment]
Read the readme carefully. You need to fetch the model.

**Comment by JRB202** [comment]
Patrick,

Read this very good article about dynamicall building of class based on
source dictionary :
https://www.dotnetcurry.com/csharp/dynamic-class-creation-roslyn

**Comment by patricoos** [comment]
You can use dictionary with this library, read documentation and take a look on repository
